### ISSUE TITLE
No instructions for setting up GFAP for use under Linux

### ISSUE THREAD

**Issue by katieemelianova** [simon19891216/GFAP#3]
Hi there,

I am attempting to run GFAP but based on the instructions in the manual, there does not seem to be any instructions on how to set anything up.

I managed to infer the directory structure expected by GFAP from the python error messages and now have something which looks like this, I am not sure whether this is correct:

```
ls go/goafter/*
go/goafter/Camellia_sinensis.txt.gz  go/goafter/go_database.txt.gz  go/goafter/pfam2go.txt.gz
```
After running the following command however, I get the following error message:

```
source/GFAP.py -aws Camellia_sinensis -go -qn test.fasta -o /lisc/user/emelianova/software/GFAP/test_out 
/bin/sh: line 1: ./bin/diamond: No such file or directory
Traceback (most recent call last):
  File "/lisc/user/emelianova/software/GFAP/source/GFAP.py", line 1311, in <module>
    align_annotation(file,inputtype,annotype,refspecies,evalue,algnment_type,algnment_percent,save,cpu,only_ID=None)
  File "/lisc/user/emelianova/software/GFAP/source/GFAP.py", line 135, in align_annotation
    annotprocess(goidfile,geneid2goid,blastfile,savefile,algnment_percent)
  File "/lisc/user/emelianova/software/GFAP/source/GFAP.py", line 84, in annotprocess
    with open(blastfile,encoding="utf-8") as f,open(savefile,"w") as f1:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/lisc/user/emelianova/software/GFAP/GFAP-blastresult.txt'
```

Do you have any other documentation that perhaps I have missed on the github explaining how to set up GFAP correctly? 

Best,

Katie

**Comment by simon19891216** [comment]
you are welcome. You can switch the directory to the same level as GFAP.py and try again.



At 2024-07-12 18:56:22, "katieemelianova" ***@***.***> wrote:

Hi there,

I am attempting to run GFAP but based on the instructions in the manual, there does not seem to be any instructions on how to set anything up.

I managed to infer the directory structure expected by GFAP from the python error messages and now have something which looks like this, I am not sure whether this is correct:

ls go/goafter/*
go/goafter/Camellia_sinensis.txt.gz  go/goafter/go_database.txt.gz  go/goafter/pfam2go.txt.gz


After running the following command however, I get the following error message:

source/GFAP.py -aws Camellia_sinensis -go -qn test.fasta -o /lisc/user/emelianova/software/GFAP/test_out 
/bin/sh: line 1: ./bin/diamond: No such file or directory
Traceback (most recent call last):
  File "/lisc/user/emelianova/software/GFAP/source/GFAP.py", line 1311, in <module>
    align_annotation(file,inputtype,annotype,refspecies,evalue,algnment_type,algnment_percent,save,cpu,only_ID=None)
  File "/lisc/user/emelianova/software/GFAP/source/GFAP.py", line 135, in align_annotation
    annotprocess(goidfile,geneid2goid,blastfile,savefile,algnment_percent)
  File "/lisc/user/emelianova/software/GFAP/source/GFAP.py", line 84, in annotprocess
    with open(blastfile,encoding="utf-8") as f,open(savefile,"w") as f1:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/lisc/user/emelianova/software/GFAP/GFAP-blastresult.txt'


Do you have any other documentation that perhaps I have missed on the github explaining how to set up GFAP correctly?

Best,

Katie

**Comment by katieemelianova** [comment]
Hi there,

As you can see from the error message I posted above, the first line is looking for a directory called "bin", within which there is the diamond executable:

```
/bin/sh: line 1: ./bin/diamond: No such file or directory
```

As you'll be aware, there is no such directory in the github repo, and consequently the final line of the error message I posted above complains that it cannot find the blast result, as a result of the missing diamond executables:

```
FileNotFoundError: [Errno 2] No such file or directory: '/lisc/user/emelianova/software/GFAP/GFAP-blastresult.txt'
```

I am therefore confused as to how switching to the directory within which GFAP.py is will help, as there are no executables of other directories located there, and I cannot see how the error messages in my original post will be solved by switching to the "source" directory within which GFAP.py is. 

Could you revisit the directory structure of GFAP and advise how to solve this in light of the actual directory structure provided in your code please,

Many thanks for your help :)

Best,

Katie

**Comment by simon19891216** [comment]
The error message means that the path of diamond is not found. When you switch the directory to the one containing GFAP.py, it enables the use of "./" which makes diamond accessible. Alternatively, you can check if there is a "bin" folder located in the same directory as GFAP.py, and within that folder, see if there is a diamond program.



At 2024-07-15 14:46:38, "katieemelianova" ***@***.***> wrote:

Hi there,

As you can see from the error message I posted above, the first line is looking for a directory called "bin", within which there is the diamond executable:

/bin/sh: line 1: ./bin/diamond: No such file or directory


As you'll be aware, there is no such directory in the github repo, and consequently the final line of the error message I posted above complains that it cannot find the blast result, as a result of the missing diamond executables:

FileNotFoundError: [Errno 2] No such file or directory: '/lisc/user/emelianova/software/GFAP/GFAP-blastresult.txt'


I am therefore confused as to how switching to the directory within which GFAP.py is will help, as there are no executables of other directories located there, and I cannot see how the error messages in my original post will be solved by switching to the "source" directory within which GFAP.py is.

Could you revisit the directory structure of GFAP and advise how to solve this in light of the actual directory structure provided in your code please,

Many thanks for your help :)

Best,

Katie

**Comment by katieemelianova** [comment]
Hi there,

Thanks for your reply, I am a little puzzled; I cloned the repo for GFAP from this git repository, and there is no bin file that I can see containing diamond (which you are able to see by simply looking through the directory structure of the GFAP github repo). Can you please point me in the direction of the instructions to configure GFAP, or if I have downloaded the code from the wrong place, the correct place from which I should obtain the GFAP package code?

Thank you!

Best,

Katie

**Comment by simon19891216** [comment]
This is indeed very strange. Based on the information you've provided, I've re-downloaded the GFAP installation package and carefully verified the contents inside, finding no issues. Please confirm that you downloaded the installation package from this link (https://github.com/simon19891216/GFAP/releases/tag/GFAP).



At 2024-07-15 17:59:48, "katieemelianova" ***@***.***> wrote:

Hi there,

Thanks for your reply, I am a little puzzled; I cloned the repo for GFAP from this git repository, and there is no bin file that I can see containing diamond (which you are able to see by simply looking through the directory structure of the GFAP github repo). Can you please point me in the direction of the instructions to configure GFAP, or if I have downloaded the code from the wrong place, the correct place from which I should obtain the GFAP package code?

Thank you!

Best,

Katie

**Comment by katieemelianova** [comment]
Hi there,

I really apologise it looks like I misunderstood the way to download the software, I was cloning the got repo, but I did not realise that I should download the package. I have down this now and it seems to be working!

I'm really grateful for your help, thanks a lot for the support with getting GFAP running.

Best,

Katie

**Comment by simon19891216** [comment]
you are welcome! and thank you for using GFAP



At 2024-07-15 22:06:56, "katieemelianova" ***@***.***> wrote:

Hi there,

I really apologise it looks like I misunderstood the way to download the software, I was cloning the got repo, but I did not realise that I should download the package. I have down this now and it seems to be working!

I'm really grateful for your help, thanks a lot for the support with getting GFAP running.

Best,

Katie
