### ISSUE TITLE
Download databases

### ISSUE THREAD

**Issue by ericgonzalezs** [simon19891216/GFAP#4]
Hi,

Could you please tell me. How I could manually download you databases?

This ftp://ftp.agis.org.cn/~panweihua/GFAP is not working for me.

**Comment by simon19891216** [comment]
You can try downloading the file from this link (http://ftp.agis.org.cn:8888/~panweihua/GFAP/). If you encounter any issues, please feel free to reach out to me directly via email at ***@***.***



At 2024-10-30 06:39:06, "ericgonzalezs" ***@***.***> wrote:

Hi,

Could you please tell me. How I could manually download you databases?

This ftp://ftp.agis.org.cn/~panweihua/GFAP is not working for me.
